services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - alfred-network
      - gateway-network

  # A2A Coordinator
  coordinator:
    build:
      context: ./agents/coordinator
      dockerfile: Dockerfile
    container_name: alfred-coordinator
    ports:
      - "8080:8080"
    environment:
      - COORDINATOR_PORT=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - alfred-network
    restart: unless-stopped

  # Alfred Assistant (to be migrated to A2A)
  alfred-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alfred-assistant
    command: ["python", "main.py", "dev"]
    ports:
      - "8000:8000" # Health endpoint
    networks:
      - alfred-network
    env_file:
      - .env.docker
    restart: unless-stopped

networks:
  alfred-network:
    driver: bridge
    name: alfred-network

  gateway-network:
    name: gateway-network
    external: true

volumes:
  caddy_data:
  caddy_config:
