services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - coral-network
      - gateway-network

  # Coral Protocol Stack
  coral-server:
    image: ams.vultrcr.com/alfred/coral-server:latest
    container_name: coral-server
    ports:
      - "5555:5555"
    networks:
      - coral-network
    volumes:
      - ./coral-application-demo-repo.yaml:/config/application.yaml

  coral-studio:
    image: ams.vultrcr.com/alfred/coral-studio:latest
    container_name: coral-studio
    ports:
      - "4173:3000"
    networks:
      - coral-network

  # Alfred Assistant
  alfred-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alfred-assistant
    command: ["python", "main.py", "dev"]
    ports:
      - "8000:8000" # Health endpoint
    networks:
      - coral-network
    env_file:
      - .env.docker
    restart: unless-stopped

networks:
  coral-network:
    driver: bridge
    name: coral-network

  gateway-network:
    name: gateway-network
    external: true

volumes:
  coral-data:
  caddy_data:
  caddy_config:
